# Generated by Django 3.2.4 on 2021-06-09 19:16

from django.db import migrations, models
import django.db.models.deletion
import location_field.models.plain


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Ime')),
                ('beggining', models.DateTimeField(verbose_name='Početak')),
                ('end', models.DateTimeField(verbose_name='Kraj')),
                ('country', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30, verbose_name='Grad')),
                ('address', models.CharField(max_length=50, verbose_name='Adresa')),
                ('location', location_field.models.plain.PlainLocationField(default='44.7857606, 20.4776834', max_length=63, verbose_name='Lokacija')),
                ('description', models.TextField(default='Detalji slede uskoro...', verbose_name='Opis')),
                ('image', models.ImageField(default='default.jpg', upload_to='images', verbose_name='Slika')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Vreme kreiranja dogadjaja')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Vreme poslednje izmene')),
            ],
            options={
                'verbose_name': 'Dogadjaj',
                'verbose_name_plural': 'Dogadjaji',
            },
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Ime')),
                ('last_name', models.CharField(max_length=50, verbose_name='Prezime')),
                ('email', models.EmailField(max_length=254, verbose_name='Emejl')),
                ('applied_at', models.DateTimeField(auto_now_add=True, verbose_name='Vreme prijave')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posetioci', to='manager.event', verbose_name='Dogadjaj')),
            ],
            options={
                'verbose_name': 'Posetilac',
                'verbose_name_plural': 'Posetioci',
            },
        ),
    ]
