# Generated by Django 3.2.4 on 2021-06-09 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_event_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='beggining',
            field=models.DateTimeField(verbose_name='Početak'),
        ),
        migrations.AlterField(
            model_name='event',
            name='city',
            field=models.CharField(max_length=30, verbose_name='Grad'),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Ime'),
        ),
    ]
